### ISSUE TITLE
SCF dependencies not resolved in AEM 6.1

### ISSUE THREAD

**Issue by gkarnik25** [Adobe-Marketing-Cloud/aem-scf-sample-components-extension#2]
The bundle for this goes into installed state as its not able to find the dependencies for SCF packages ( com.adobe.cq.social.commons.client.api &
com.adobe.cq.social.commons.client.endpoints ) in 6.1. The code works well in 6.0, can you guys please look into it. 

![scf-extension-bundles-not-installed](https://cloud.githubusercontent.com/assets/6148947/11363834/487f0fb0-92c2-11e5-91cd-ac96bd86da8d.png)

**Comment by jhelbert2012** [comment]
I made some changes for working with AEM 6.1 https://github.com/jhelbert2012/aem-scf-sample-components-extension

**Comment by sid-p** [comment]
the code has been updated to the latest api jar compatible with the latest FP released for AE< 6.2
